---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repar
  labels:
    app: repar
spec:
  selector:
    matchLabels:
          app: repar
  replicas: 1
  template:
    metadata:
      labels:
        app: repar # This label identifies our application, used for filtering output
    spec:
      # securityContext: # Best practice for security - if possible never run as root (which is default)
      # runAsNonRoot: true
      restartPolicy: Always
      containers:
        - name: repar
          image: k8s.gcr.io/busybox
          # command: ["/bin/sh", "-c", "cp /standalone/configmap/* /standalone/config"]
          command: ["/bin/sh", "-c", "--"]
          args: ["while true; do sleep 30; while IFS= read -r line; do echo $line; done < /bbconfig.json;done;"]
          volumeMounts:
            - name: from-configmap
              mountPath: /bbconfig.json
              subPath: bbconfig.json
      volumes:
        - name: from-configmap
          configMap: 
            name: repar-configmap
